# -*- mode: ruby -*-
# vi: set ft=ruby :

# I use this for OSS SVG development because that requires Inkscape
# v0.47 (due to limitations of our production CentOS VMs) and the last
# version of Ubuntu that supported Inkscape v0.47 was Ubuntu 14.04.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "bento/ubuntu-14.04"

  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "file", source: "~/.gnupg/pubring.gpg", destination: "~/.gnupg/pubring.gpg"
  config.vm.provision "file", source: "~/.gnupg/secring.gpg", destination: "~/.gnupg/secring.gpg"
  config.vm.provision "file", source: "~/.gnupg/trustdb.gpg", destination: "~/.gnupg/trustdb.gpg"
  config.vm.provision "shell", privileged: false, inline: 'chmod -R go-rwx ~/.ssh ~/.gnupg'
  config.vm.provision "shell", privileged: true, path: "bin/bootstrap-puppet"
  config.vm.provision :puppet
  config.vm.provision 'shell', privileged: false, path: "bin/print-manual-setup-steps"

  config.ssh.forward_x11 = true
end
