# -*- mode: ruby -*-

# From https://gorails.com/guides/using-vagrant-for-rails-development

VAGRANTFILE_API_VERSION = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty32"

  # Configurate the virtual machine to use 2GB of RAM
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Forward the Rails server default port to the host
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  # Fix networking issue. From
  # https://github.com/Varying-Vagrant-Vagrants/VVV/issues/375
  config.vm.provider "virtualbox" do |vb|
    ### Change network card to PCnet-FAST III
    # For NAT adapter
    vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
    # For host-only adapter
    vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
  end

  # Use Chef Solo to provision our virtual machine
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks", "site-cookbooks"]

    chef.add_recipe "apt"
    chef.add_recipe "nodejs"
    chef.add_recipe "ruby_build"
    chef.add_recipe "mysql::server"
    chef.add_recipe "mysql::client"
    chef.add_recipe "emacs24"
    chef.add_recipe "rvm::system"

    chef.json = {
      rvm: {
        default_ruby: "ruby-2.2.2",
        rvmrc: {
          # https://github.com/martinisoft/chef-rvm/issues/296
          rvm_gemset_create_on_use_flag: 1
        }
      },
      mysql: {
        server_root_password: ''
      }
    }
  end
end
