# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty32"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000, auto_correct: true

  # Fix networking issue. From https://github.com/Varying-Vagrant-Vagrants/VVV/issues/375
  config.vm.provider "virtualbox" do |vb|
    # Change network card to PCnet-FAST III.
    vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"] # NAT adapter
    vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"] # Host-only adapter
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "shell", privileged: false, inline: 'chmod -R go-rwx ~/.ssh'

  config.vm.provision :shell, inline: <<'EOT'
    mkdir -p /etc/puppet/modules
    for n in arioch-redis \
             maestrodev-rvm \
             willdurand-nodejs \
             puppetlabs-mysql
    do
      (puppet module list | grep $n) || puppet module install $n
    done
EOT

  config.vm.provision :puppet

  config.vm.provision 'shell', privileged: false, inline: <<'EOT'
    echo '!'
    echo '!'
    echo 'If this is a brand new VM, then run this in the VM:'
    echo '    exec $(ssh-agent -s)'
    echo '    ssh-add'
    echo '    (cd ~/ && git clone git@github.com:officespacesoftware/huddle.git config &&  for f in config/.??* ; do rm -f $f; ln -s $f; done)'
    echo '    (mkdir -p ~/projects/oss/huddle && cd ~/projects/oss && git clone git@github.com:officespacesoftware/huddle.git huddle)'
    echo '    (cd ~/projects/oss/huddle && gem install bundle && bundle)'
    echo '    # mysql officespace_development; source db/structure.sql; then run db:migrate'
EOT
end
